### ISSUE TITLE
Application does not render in IE/Edge

### ISSUE THREAD

**Issue by chelfenbein** [inertiajs/pingcrm#28]
After installing the Ping CRM demo application according to the documentation it works as expected in Firefox and Google Chrome browsers, but when trying to access it in IE/Edge the application does not render and the Javascript console shows the following error:

**"SCRIPT1028: SCRIPT1028: Expected identifier, string or number" app.js (522, 1)**
```
"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var axios__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! axios */ \"./node_modules/axios/index.js\");\n/* harmony import */ var […]
```
I've experienced the same issue with another application I've migrated to InertiaJS so it might be a general issue with InertiaJS.

**Comment by reinink** [comment]
Hmm, interesting. Some quick Google search seems to suggest this is a trailing comma issue. For example:

```js
var obj = {
   id: 123,
   name: 'bla',  <--
}
```

I'll have to test this manually and see if I can track down the issue.

**Comment by zappzerapp** [comment]
+1

**Comment by chelfenbein** [comment]
Any udates on this issue?

I would really appreciate to use this amazing library in the software I'm currently working on.
But the planned relase date is in august 2019 and it has to run in every current browser.

Anyway, keep up the excellent work. :)

**Comment by EloD10** [comment]
Adding this code into `webpack.mix.js` worked well for me. (checked on Edge only)
```js
    module: {
      rules: [{
        test: /\.js?$/,
        use: [{
          loader: 'babel-loader',
          options: mix.config.babel()
        }]
      }]
    },
```

**Comment by zappzerapp** [comment]
@EloD10, I'm not sure what I did wrong, but if I add in `.webpackConfig` after `resolve: {...},` I can't compile it anymore.

[fail.txt](https://github.com/inertiajs/pingcrm/files/3439349/fail.txt)
[webpack.mix.js.txt](https://github.com/inertiajs/pingcrm/files/3439350/webpack.mix.js.txt)

**Comment by chelfenbein** [comment]
@EloD10
Thank you very much. Your solution helped me with slightly modifications to solve the rendering issues of my InertiaJS applications in IE and Edge browsers.

webpack.mix.js:
```
module: {
    rules: [{
        test: /\.js$/,
        use: {
            loader: 'babel-loader',
            options: {
                presets: ['@babel/preset-env']
            }
        }
    }]
}
```
.babelrc:
```
{
    "plugins": ["@babel/plugin-syntax-dynamic-import"]
}
```
package.json:
```
"@babel/core": "^7.5.4",
"@babel/preset-env": "^7.5.4",
"@babel/plugin-syntax-dynamic-import": "^7.2.0",
"babel-polyfill": "^6.26.0",
```
Polyfill was necessary in my setup to achieve compatibility with IE.

**Comment by zappzerapp** [comment]
Yeah, it looks good now. Thank you @chelfenbein

**Comment by sebastiandedeyne** [comment]
This is caused by inertiajs/inertia#54, and will be solved when version 0.1 is released!

Note that some polyfills might always be necessary, but we'll document those in the future.

**Comment by sebastiandedeyne** [comment]
Inertia 0.1 has been released, so this is solved!

**Comment by paulotra** [comment]
It still doesn't work on my end, do i have to place it after `resolve` or does it work interchangeably? I also am getting  this error.

![image](https://user-images.githubusercontent.com/20724804/68390371-2081e400-01a0-11ea-92c4-79a706b52c10.png)

**Comment by paulotra** [comment]
@zappzerapp do you still need to import babel-polyfill in webpack.mix.js?

**Comment by zappzerapp** [comment]
@paulotra i had to extend the webpack.mix.js by the following code

```
    module: {
      rules: [{
        test: /\.js$/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
      }],
    },
``` 
Besides, I had to add `require("es6-promise").polyfill();` to the app.js
